### ISSUE TITLE
Import Error on ei.fit

### ISSUE THREAD

**Issue by qu-genesis** [mggg/ecological-inference#112]
Hello! I'm running into an error when I run the ei.fit() function. I'm not sure I fully understand where the error comes from. 

I first tried to run a RxC EI on my own data, then a 2x2 EI on my data and saw the same error. Then I tried running the santa_clara_demo_r_by_c.ipynb and got the same error. I'm hoping you might point out if there's any package I did not install or what else might be going on. Below is the error I get when I call the fit function. I think it gives this error for every iteration because I get many of these for one call. 

I'm running on Python 3.10.6 with pyei==1.0.1 and pymc==4.0.0.b5 

Thank you so much.

```
{
	"name": "ImportError",
	"message": "dlopen(/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so, 0x0002): tried: '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (no such file), '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Apply node that caused the error: InplaceDimShuffle{x,x}(TensorConstant{1})
Toposort index: 0
Inputs types: [TensorType(int8, ())]

Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py\", line 1723, in point_logps
    factor_logps_fn = [at.sum(factor) for factor in self.logpt(factors, sum=False)]
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py\", line 757, in logpt
    rv_logps = joint_logpt(list(rv_values.keys()), rv_values, sum=False, jacobian=jacobian)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/logprob.py\", line 223, in joint_logpt
    temp_logp_var_dict = factorized_joint_logprob(
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/aeppl/joint_logprob.py\", line 186, in factorized_joint_logprob
    q_logprob_vars = _logprob(
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/functools.py\", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/distribution.py\", line 123, in logp
    return class_logp(value, *dist_params)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/multivariate.py\", line 586, in logp
    res = factln(n) + at.sum(-factln(value) + logpow(p, value), axis=-1)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/dist_math.py\", line 79, in factln
    return gammaln(n + 1)

HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/vm.py:1112, in VMLinker.make_all(self, profiler, input_storage, output_storage, storage_map)
   1108 # no-recycling is done at each VM.__call__ So there is
   1109 # no need to cause duplicate c code by passing
   1110 # no_recycling here.
   1111 thunks.append(
-> 1112     node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
   1113 )
   1114 linker_make_thunk_time[node] = time.time() - thunk_start

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/op.py:131, in COp.make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    130 try:
--> 131     return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
    132 except (NotImplementedError, MethodNotDefined):
    133     # We requested the c code, so don't catch the error.

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/op.py:96, in COp.make_c_thunk(self, node, storage_map, compute_map, no_recycling)
     95         raise NotImplementedError(\"float16\")
---> 96 outputs = cl.make_thunk(
     97     input_storage=node_input_storage, output_storage=node_output_storage
     98 )
     99 thunk, node_input_filters, node_output_filters = outputs

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1198, in CLinker.make_thunk(self, input_storage, output_storage, storage_map)
   1197 init_tasks, tasks = self.get_init_tasks()
-> 1198 cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1199     input_storage, output_storage, storage_map
   1200 )
   1202 res = _CThunk(cthunk, init_tasks, tasks, error_storage, module)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1133, in CLinker.__compile__(self, input_storage, output_storage, storage_map)
   1132 output_storage = tuple(output_storage)
-> 1133 thunk, module = self.cthunk_factory(
   1134     error_storage,
   1135     input_storage,
   1136     output_storage,
   1137     storage_map,
   1138 )
   1139 return (
   1140     thunk,
   1141     module,
   (...)
   1150     error_storage,
   1151 )

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1629, in CLinker.cthunk_factory(self, error_storage, in_storage, out_storage, storage_map)
   1628         node.op.prepare_node(node, storage_map, None, \"c\")
-> 1629     module = get_module_cache().module_from_key(key=key, lnk=self)
   1631 vars = self.inputs + self.outputs + self.orphans

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:1219, in ModuleCache.module_from_key(self, key, lnk)
   1218 location = dlimport_workdir(self.dirname)
-> 1219 module = lnk.compile_cmodule(location)
   1220 name = module.__file__

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1538, in CLinker.compile_cmodule(self, location)
   1537     _logger.debug(f\"LOCATION {location}\")
-> 1538     module = c_compiler.compile_str(
   1539         module_name=mod.code_hash,
   1540         src_code=src_code,
   1541         location=location,
   1542         include_dirs=self.header_dirs(),
   1543         lib_dirs=self.lib_dirs(),
   1544         libs=libs,
   1545         preargs=preargs,
   1546     )
   1547 except Exception as e:

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:2589, in GCC_compiler.compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2588 assert os.path.isfile(lib_filename)
-> 2589 return dlimport(lib_filename)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:322, in dlimport(fullpath, suffix)
    321     warnings.filterwarnings(\"ignore\", message=\"numpy.ndarray size changed\")
--> 322     rval = __import__(module_name, {}, {}, [module_name])
    323 t1 = time.time()

ImportError: dlopen(/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so, 0x0002): tried: '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (no such file), '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
/Users/genesisqu/Downloads/santa_clara_demo_r_by_c.ipynb Cell 7 line <cell line: 1>()
----> <a href='vscode-notebook-cell:/Users/genesisqu/Downloads/santa_clara_demo_r_by_c.ipynb#W6sZmlsZQ%3D%3D?line=0'>1</a> ei.fit(group_fractions, votes_fractions, precinct_pops, demographic_group_names, candidate_names)

File ~/opt/miniconda3/lib/python3.10/site-packages/pyei/r_by_c.py:198, in RowByColumnEI.fit(self, group_fractions, votes_fractions, precinct_pops, demographic_group_names, candidate_names, target_accept, tune, draw_samples, precinct_names, **other_sampling_args)
    193 if self.model_name in [
    194     \"multinomial-dirichlet-modified\",
    195     \"multinomial-dirichlet\",
    196 ]:  # for models whose sampling is w/ pycm
    197     with self.sim_model:  # pylint: disable=not-context-manager
--> 198         self.sim_trace = sampling_jax.sample_numpyro_nuts(
    199             target_accept=target_accept, tune=tune, **other_sampling_args
    200         )
    201 elif self.model_name == \"greiner-quinn\":
    202     self.sim_trace = pyei_greiner_quinn_sample(
    203         group_fractions, votes_fractions, precinct_pops, **other_sampling_args
    204     )  #

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/sampling_jax.py:467, in sample_numpyro_nuts(draws, tune, chains, target_accept, random_seed, initvals, model, var_names, progress_bar, keep_untransformed, chain_method, idata_kwargs, nuts_kwargs)
    464 tic1 = datetime.now()
    465 print(\"Compiling...\", file=sys.stdout)
--> 467 init_params = _get_batched_jittered_initial_points(
    468     model=model,
    469     chains=chains,
    470     initvals=initvals,
    471     random_seed=random_seed,
    472 )
    474 logp_fn = get_jaxified_logp(model, negative_logp=False)
    476 if nuts_kwargs is None:

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/sampling_jax.py:167, in _get_batched_jittered_initial_points(model, chains, initvals, random_seed, jitter, jitter_max_retries)
    163 random_seed = np.random.default_rng(random_seed).integers(2**30, size=chains)
    165 assert len(random_seed) == chains
--> 167 initial_points = _init_jitter(
    168     model,
    169     initvals,
    170     seeds=random_seed,
    171     jitter=jitter,
    172     jitter_max_retries=jitter_max_retries,
    173 )
    174 initial_points = [list(initial_point.values()) for initial_point in initial_points]
    175 if chains == 1:

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/sampling.py:2194, in _init_jitter(model, initvals, seeds, jitter, jitter_max_retries)
   2192 if i < jitter_max_retries:
   2193     try:
-> 2194         model.check_start_vals(point)
   2195     except SamplingError:
   2196         # Retry with a new seed
   2197         seed = rng.randint(2**30, dtype=np.int64)

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py:1687, in Model.check_start_vals(self, start)
   1681     valid_keys = \", \".join(self.named_vars.keys())
   1682     raise KeyError(
   1683         \"Some start parameters do not appear in the model!\
\"
   1684         f\"Valid keys are: {valid_keys}, but {extra_keys} was supplied\"
   1685     )
-> 1687 initial_eval = self.point_logps(point=elem)
   1689 if not all(np.isfinite(v) for v in initial_eval.values()):
   1690     raise SamplingError(
   1691         \"Initial evaluation of model at starting point failed!\
\"
   1692         f\"Starting values:\
{elem}\
\
\"
   1693         f\"Initial evaluation results:\
{initial_eval}\"
   1694     )

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py:1728, in Model.point_logps(self, point, round_vals)
   1722 factors = self.basic_RVs + self.potentials
   1723 factor_logps_fn = [at.sum(factor) for factor in self.logpt(factors, sum=False)]
   1724 return {
   1725     factor.name: np.round(np.asarray(factor_logp), round_vals)
   1726     for factor, factor_logp in zip(
   1727         factors,
-> 1728         self.compile_fn(factor_logps_fn)(point),
   1729     )
   1730 }

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py:1524, in Model.compile_fn(self, outs, inputs, mode, point_fn, **kwargs)
   1521     inputs = inputvars(outs)
   1523 with self:
-> 1524     fn = compile_pymc(
   1525         inputs,
   1526         outs,
   1527         allow_input_downcast=True,
   1528         accept_inplace=True,
   1529         mode=mode,
   1530         **kwargs,
   1531     )
   1533 if point_fn:
   1534     return PointFunc(fn)

File ~/opt/miniconda3/lib/python3.10/site-packages/pymc/aesaraf.py:996, in compile_pymc(inputs, outputs, mode, **kwargs)
    994 opt_qry = mode.provided_optimizer.including(\"random_make_inplace\", check_parameter_opt)
    995 mode = Mode(linker=mode.linker, optimizer=opt_qry)
--> 996 aesara_function = aesara.function(
    997     inputs,
    998     outputs,
    999     updates={**rng_updates, **kwargs.pop(\"updates\", {})},
   1000     mode=mode,
   1001     **kwargs,
   1002 )
   1003 return aesara_function

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/compile/function/__init__.py:337, in function(inputs, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input)
    331     fn = orig_function(
    332         inputs, outputs, mode=mode, accept_inplace=accept_inplace, name=name
    333     )
    334 else:
    335     # note: pfunc will also call orig_function -- orig_function is
    336     #      a choke point that all compilation must pass through
--> 337     fn = pfunc(
    338         params=inputs,
    339         outputs=outputs,
    340         mode=mode,
    341         updates=updates,
    342         givens=givens,
    343         no_default_updates=no_default_updates,
    344         accept_inplace=accept_inplace,
    345         name=name,
    346         rebuild_strict=rebuild_strict,
    347         allow_input_downcast=allow_input_downcast,
    348         on_unused_input=on_unused_input,
    349         profile=profile,
    350         output_keys=output_keys,
    351     )
    352 return fn

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/compile/function/pfunc.py:363, in pfunc(params, outputs, mode, updates, givens, no_default_updates, accept_inplace, name, rebuild_strict, allow_input_downcast, profile, on_unused_input, output_keys)
    350     profile = ProfileStats(message=profile)
    352 inputs, cloned_outputs = construct_pfunc_ins_and_outs(
    353     params,
    354     outputs,
   (...)
    360     allow_input_downcast,
    361 )
--> 363 return orig_function(
    364     inputs,
    365     cloned_outputs,
    366     mode,
    367     accept_inplace=accept_inplace,
    368     name=name,
    369     profile=profile,
    370     on_unused_input=on_unused_input,
    371     output_keys=output_keys,
    372 )

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/compile/function/types.py:1743, in orig_function(inputs, outputs, mode, accept_inplace, name, profile, on_unused_input, output_keys)
   1732     m = Maker(
   1733         inputs,
   1734         outputs,
   (...)
   1740         name=name,
   1741     )
   1742     with config.change_flags(compute_test_value=\"off\"):
-> 1743         fn = m.create(defaults)
   1744 finally:
   1745     t2 = time.time()

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/compile/function/types.py:1638, in FunctionMaker.create(self, input_storage, trustme, storage_map)
   1635 start_import_time = aesara.link.c.cmodule.import_time
   1637 with config.change_flags(traceback__limit=config.traceback__compile_limit):
-> 1638     _fn, _i, _o = self.linker.make_thunk(
   1639         input_storage=input_storage_lists, storage_map=storage_map
   1640     )
   1642 end_linker = time.time()
   1644 linker_time = end_linker - start_linker

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/basic.py:254, in LocalLinker.make_thunk(self, input_storage, output_storage, storage_map, **kwargs)
    247 def make_thunk(
    248     self,
    249     input_storage: Optional[\"InputStorageType\"] = None,
   (...)
    252     **kwargs,
    253 ) -> Tuple[\"BasicThunkType\", \"InputStorageType\", \"OutputStorageType\"]:
--> 254     return self.make_all(
    255         input_storage=input_storage,
    256         output_storage=output_storage,
    257         storage_map=storage_map,
    258     )[:3]

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/vm.py:1121, in VMLinker.make_all(self, profiler, input_storage, output_storage, storage_map)
   1119             thunks[-1].lazy = False
   1120     except Exception:
-> 1121         raise_with_op(fgraph, node)
   1123 t1 = time.time()
   1125 if self.profile:

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/utils.py:538, in raise_with_op(fgraph, node, thunk, exc_info, storage_map)
    533     warnings.warn(
    534         f\"{exc_type} error does not allow us to add an extra error message\"
    535     )
    536     # Some exception need extra parameter in inputs. So forget the
    537     # extra long error message in that case.
--> 538 raise exc_value.with_traceback(exc_trace)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/vm.py:1112, in VMLinker.make_all(self, profiler, input_storage, output_storage, storage_map)
   1107 thunk_start = time.time()
   1108 # no-recycling is done at each VM.__call__ So there is
   1109 # no need to cause duplicate c code by passing
   1110 # no_recycling here.
   1111 thunks.append(
-> 1112     node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
   1113 )
   1114 linker_make_thunk_time[node] = time.time() - thunk_start
   1115 if not hasattr(thunks[-1], \"lazy\"):
   1116     # We don't want all ops maker to think about lazy Ops.
   1117     # So if they didn't specify that its lazy or not, it isn't.
   1118     # If this member isn't present, it will crash later.

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/op.py:131, in COp.make_thunk(self, node, storage_map, compute_map, no_recycling, impl)
    127 self.prepare_node(
    128     node, storage_map=storage_map, compute_map=compute_map, impl=\"c\"
    129 )
    130 try:
--> 131     return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
    132 except (NotImplementedError, MethodNotDefined):
    133     # We requested the c code, so don't catch the error.
    134     if impl == \"c\":

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/op.py:96, in COp.make_c_thunk(self, node, storage_map, compute_map, no_recycling)
     94         print(f\"Disabling C code for {self} due to unsupported float16\")
     95         raise NotImplementedError(\"float16\")
---> 96 outputs = cl.make_thunk(
     97     input_storage=node_input_storage, output_storage=node_output_storage
     98 )
     99 thunk, node_input_filters, node_output_filters = outputs
    101 @is_cthunk_wrapper_type
    102 def rval():

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1198, in CLinker.make_thunk(self, input_storage, output_storage, storage_map)
   1170 \"\"\"
   1171 Compiles this linker's fgraph and returns a function to perform the
   1172 computations, as well as lists of storage cells for both the inputs
   (...)
   1195   first_output = ostor[0].data
   1196 \"\"\"
   1197 init_tasks, tasks = self.get_init_tasks()
-> 1198 cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
   1199     input_storage, output_storage, storage_map
   1200 )
   1202 res = _CThunk(cthunk, init_tasks, tasks, error_storage, module)
   1203 res.nodes = self.node_order

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1133, in CLinker.__compile__(self, input_storage, output_storage, storage_map)
   1131 input_storage = tuple(input_storage)
   1132 output_storage = tuple(output_storage)
-> 1133 thunk, module = self.cthunk_factory(
   1134     error_storage,
   1135     input_storage,
   1136     output_storage,
   1137     storage_map,
   1138 )
   1139 return (
   1140     thunk,
   1141     module,
   (...)
   1150     error_storage,
   1151 )

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1629, in CLinker.cthunk_factory(self, error_storage, in_storage, out_storage, storage_map)
   1627     for node in self.node_order:
   1628         node.op.prepare_node(node, storage_map, None, \"c\")
-> 1629     module = get_module_cache().module_from_key(key=key, lnk=self)
   1631 vars = self.inputs + self.outputs + self.orphans
   1632 # List of indices that should be ignored when passing the arguments
   1633 # (basically, everything that the previous call to uniq eliminated)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:1219, in ModuleCache.module_from_key(self, key, lnk)
   1217 try:
   1218     location = dlimport_workdir(self.dirname)
-> 1219     module = lnk.compile_cmodule(location)
   1220     name = module.__file__
   1221     assert name.startswith(location)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/basic.py:1538, in CLinker.compile_cmodule(self, location)
   1536 try:
   1537     _logger.debug(f\"LOCATION {location}\")
-> 1538     module = c_compiler.compile_str(
   1539         module_name=mod.code_hash,
   1540         src_code=src_code,
   1541         location=location,
   1542         include_dirs=self.header_dirs(),
   1543         lib_dirs=self.lib_dirs(),
   1544         libs=libs,
   1545         preargs=preargs,
   1546     )
   1547 except Exception as e:
   1548     e.args += (str(self.fgraph),)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:2589, in GCC_compiler.compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2587 open(os.path.join(location, \"__init__.py\"), \"w\").close()
   2588 assert os.path.isfile(lib_filename)
-> 2589 return dlimport(lib_filename)

File ~/opt/miniconda3/lib/python3.10/site-packages/aesara/link/c/cmodule.py:322, in dlimport(fullpath, suffix)
    320 with warnings.catch_warnings():
    321     warnings.filterwarnings(\"ignore\", message=\"numpy.ndarray size changed\")
--> 322     rval = __import__(module_name, {}, {}, [module_name])
    323 t1 = time.time()
    324 import_time += t1 - t0

ImportError: dlopen(/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so, 0x0002): tried: '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (no such file), '/Users/genesisqu/.aesara/compiledir_macOS-13.5.1-arm64-i386-64bit-i386-3.10.6-64/tmpjnuxm12w/mba10987274f369529454d4a60996746c3927712a0b1b3928446a3c275151e2ee.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
Apply node that caused the error: InplaceDimShuffle{x,x}(TensorConstant{1})
Toposort index: 0
Inputs types: [TensorType(int8, ())]

Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py\", line 1723, in point_logps
    factor_logps_fn = [at.sum(factor) for factor in self.logpt(factors, sum=False)]
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/model.py\", line 757, in logpt
    rv_logps = joint_logpt(list(rv_values.keys()), rv_values, sum=False, jacobian=jacobian)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/logprob.py\", line 223, in joint_logpt
    temp_logp_var_dict = factorized_joint_logprob(
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/aeppl/joint_logprob.py\", line 186, in factorized_joint_logprob
    q_logprob_vars = _logprob(
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/functools.py\", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/distribution.py\", line 123, in logp
    return class_logp(value, *dist_params)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/multivariate.py\", line 586, in logp
    res = factln(n) + at.sum(-factln(value) + logpow(p, value), axis=-1)
  File \"/Users/genesisqu/opt/miniconda3/lib/python3.10/site-packages/pymc/distributions/dist_math.py\", line 79, in factln
    return gammaln(n + 1)

HINT: Use a linker other than the C linker to print the inputs' shapes and strides.
HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node."
}
```

**Comment by qu-genesis** [comment]
Additionally, when I tried to run the Intro-to-PyEI notebook on Colab, I got this error

`AttributeError: module 'jax.numpy' has no attribute 'product'`

Is there a workaround for this? My jax and jaxlib versions are 0.4.19. Thank you!

**Comment by eveomett** [comment]
I have the same issue.  After finding this: [https://github.com/pymc-devs/pymc/issues/6964](https://github.com/pymc-devs/pymc/issues/6964) I used ```!pip install 'pymc>=5.9'``` and am no longer having that error.  (However when I used ```!pip install 'pymc>=5.9'``` I did get the error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyei 1.0.1 requires pymc==4.0.0b5, but you have pymc 5.10.3 which is incompatible.
```
Nevertheless so far it seems to be working with pymc 5.10.3.  I'd also love to hear if there's a fix that doesn't involve creating the above error.

**Comment by AudenCote** [comment]
I hit the same problem as @eveomett after fixing the jax issue, and pymc 5.10.3 indeed works for me in the 2x2 model, but when running the r x c model (with the example code) I get:

```
Traceback (most recent call last):
  File "/Users/acl/Desktop/UMass/Chin/Redistricting/Preliminary/NC_CaseStudy/EI_MRP/PyEI/ecological-inference-main/EI_MRP.py", line 29, in <module>
    ei_rbyc.fit(group_fractions_rbyc, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acl/Desktop/UMass/Chin/Redistricting/Preliminary/NC_CaseStudy/EI_MRP/PyEI/ecological-inference-main/pyei/r_by_c.py", line 178, in fit
    self.sim_model = ei_multinom_dirichlet_modified(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/acl/Desktop/UMass/Chin/Redistricting/Preliminary/NC_CaseStudy/EI_MRP/PyEI/ecological-inference-main/pyei/r_by_c_models.py", line 109, in ei_multinom_dirichlet_modified
    phi_kappa = pm.Deterministic("phi_kappa", at.transpose(kappa * at.transpose(phi)))
                                                                   ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aesara/tensor/basic.py", line 1931, in transpose
    ret = DimShuffle(x.broadcastable, axes)(x)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aesara/graph/op.py", line 294, in __call__
    node = self.make_node(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aesara/tensor/elemwise.py", line 188, in make_node
    input = as_tensor_variable(_input)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aesara/tensor/__init__.py", line 42, in as_tensor_variable
    return _as_tensor_variable(x, name, ndim, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/aesara/tensor/__init__.py", line 49, in _as_tensor_variable
    raise NotImplementedError(f"Cannot convert {x} to a tensor variable.")
NotImplementedError: Cannot convert phi to a tensor variable.
```

I pulled down the source code to see if it was an easy fix, and looking [here](https://discourse.pymc.io/t/notimplementederror-cannot-convert-rv-to-a-tensor-variable-inside-pm-deterministic/11280), I saw that this is because in this later version of pymc, pytensor is needed rather than aesara. So in the file r_by_c_models.py I replaced

`import aesara.tensor as at`

with 

`import pytensor.tensor as pt`

And replaced line 110 with

`phi_kappa = pm.Deterministic("phi_kappa", pt.transpose(kappa * pt.transpose(phi)))`

And when I now run the test code for the r_x_c model, it works no problem and gives the same results as reported in the ipynb guides.

**Comment by karink520** [comment]
Thanks for raising this issue with the requirements versioning! I updated the requirements to use pymc 5 (and pytensor instead of aesara) so that hopefully other folks won't run into this issue. I'll put the fixed version on pypi within a day or so as well.

I'm closing this for now since I think it's all set, but feel free to re-open if there's still a problem.
